"""LexID initialization module."""
from .core import (
    ArticleChunk,
    Citation,
    VerificationResult,
    VerifiedAnswer,
    ArticleStatus,
    parse_articles,
    VersionGraph,
    HybridRetriever,
    CitationVerifier,
    is_in_scope,
    build_verified_answer,
    QueryPlan,
    HeuristicLegalPlanner,
    PlannedRetriever,
    DenseHybridRetriever,
    reciprocal_rank_fusion,
    SynthesizedAnswer,
    verify_synthesized_answer,
    EvaluationCase,
    EvaluationResult,
    compute_evaluation_metrics,
)

__all__ = [
    "ArticleChunk",
    "Citation",
    "VerificationResult",
    "VerifiedAnswer",
    "ArticleStatus",
    "parse_articles",
    "VersionGraph",
    "HybridRetriever",
    "CitationVerifier",
    "is_in_scope",
    "build_verified_answer",
    "QueryPlan",
    "HeuristicLegalPlanner",
    "PlannedRetriever",
    "DenseHybridRetriever",
    "reciprocal_rank_fusion",
    "SynthesizedAnswer",
    "verify_synthesized_answer",
    "EvaluationCase",
    "EvaluationResult",
    "compute_evaluation_metrics",
]
